### PR TITLE
alternative implementation for #122

### PR DESCRIPTION
**Pull request by rhaschke**
refactored `main()` into:
- process_doc_with_error_handling(input_file_name, **kwargs)
- catch forwarded exceptions and gracefully exit
- writing output

This has the following benefits compared to your approach:
- handling of just_deps and just_includes stays in main / cli only
- common exception handling

If you like this approach, go ahead and merge this into your [PR #122](https://github.com/ros/xacro/pull/122).

### CODE REVIEW

**Comment by peci1** [comment]
Thanks, but I'd like to make clear a few things about this proposal.

1) It changes behavior: before, the banner was not included when just_includes is True, whereas the proposed code includes it every time.

2) Why should I want a Python library to write something to the console? When calling a function, I want to get an exception, and not a printout to stderr. The only thing I might be missing is the filestack, but I can actually get it if I really want to.

3) Why should just_deps or just_includes be only handled by CLI? I can imagine someone wants to use them even using the Python API.

**Comment by rhaschke** [comment]
I agree that a python library should do exception handling itself. For some reason I thought that your PR tried to wrap the exception handling within `convert()` too. However, if you want to simply process a document with your own exception handling, then I would propose to use the [few lines of code proposed before](https://github.com/ros/xacro/pull/122#issuecomment-161905516). 
My PR proposal was an attempt to wrap the exception handling into a re-usable function, which I would consider the only missing part. 
IMHO a python library should not request the converted string, but the XML document for further processing.
For the same reason, just_deps and just_includes options shouldn't return a string, but the list of includes or the XML document.
Both data items are accessible with the existing API, though the code might be hidden in `main()`.
Hence, I suggest to simply improve documentation.

**Comment by peci1** [comment]
You're right, returning the XML doc is even better than returning it as a string.

Thus, it'd simplify to 2 lines of code, and that's ok for me if we document it well (bot on the ROS wiki and in the source code). The only thing is the Python-generated files would not have the banner included, but that might be a negligible issue.

One more question: the `restore_filestack([filename])` call is not needed before parsing?

**Comment by rhaschke** [comment]
`restore_filestack([filename])` is indeed needed to correctly initialize the file stack for error reporting.
That's important in case the opening or parsing of filename fails. I finally decided to summarize the three function calls in a new function `process_file()`. However, this is now much simpler than your initial proposal.
I will PR my latest changes directly to ros/xacro.

**Comment by peci1** [comment]
Okay, great! Thanks.

**Pull request closed without merging**
